version: '3'

services:
  mongo:
    image: mongo
    container_name: ca-mongo
    volumes:
      - ./db:/data/db
    logging:
      driver: none
  idxMongo:
    image: mongo
    container_name: ca-idx
    links:
      - mongo
    volumes:
      - ./config:/config
    command:
      - /config/run_idx.sh
    depends_on:
      - mongo
  bindaas:
    build: "./Deps/Bindaas/"
    depends_on:
      - "mongo"
    container_name: ca-data
    logging:
      driver: none
    ports: ["8080:8080", "9099:9099"]
    volumes:
      - ./config/bindaas_projects/:/root/bindaas/bin/projects/
      - ./config/bindaas.config.json:/root/bindaas/bin/bindaas.config.json
  iip:
    build: "https://github.com/camicroscope/iipImage.git#release"
    container_name: ca-iip
    volumes:
      - ./images/:/data/images/
  viewer:
    build: "https://github.com/camicroscope/caMicroscope.git#develop"
    container_name: ca-front
    logging:
      driver: none
  loader:
    build: "https://github.com/camicroscope/SlideLoader.git#release"
    container_name: ca-load
    logging:
      driver: none
    volumes:
      - ./images/:/images/
  elevate:
    build: "https://github.com/camicroscope/Security.git#develop"
    container_name: ca-security
    ports: ["4010:4010"]
    volumes:
      - ./config/routes.json:/root/src/routes.json
    environment:
      - DISABLE_SEC=true
  auth:
    build: "./Deps/auth_service/"
    container_name: ca-auth
    logging:
      driver: none
  pathdb:
    build: "https://github.com/SBU-BMI/PathDB.git#develop"
    container_name: quip-pathdb
    ports: ["8887:80"]
    volumes:
      - ./data:/data/
      - ./images/:/data/pathdb/files/wsi
      - ./jwt_keys/:/keys/
      - ./config:/config
    command:
      - /config/pathdb_pre.sh

